### ISSUE TITLE
小米r3d安装后出错

### ISSUE THREAD

**Issue by lvxj11** [xzhih/ONMP#11]
安装后探针可以打开
但phpMyAdmin和nextcloud都打不开，其他还没试。
这是phpMyAdmin
Fatal error: Uncaught Error: Call to undefined function Symfony\Polyfill\Mbstring\iconv_strpos() in /opt/wwwroot/phpMyAdmin/vendor/symfony/polyfill-mbstring/Mbstring.php:490 Stack trace: #0 /opt/wwwroot/phpMyAdmin/vendor/symfony/polyfill-mbstring/bootstrap.php(34): Symfony\Polyfill\Mbstring\Mbstring::mb_strpos('&', ';', 0, 'UTF-8') #1 /opt/wwwroot/phpMyAdmin/libraries/classes/Url.php(248): mb_strpos('&', ';') #2 /opt/wwwroot/phpMyAdmin/libraries/classes/Url.php(201): PhpMyAdmin\Url::getArgSeparator() #3 /opt/wwwroot/phpMyAdmin/libraries/classes/Url.php(166): PhpMyAdmin\Url::getCommonRaw(Array, '?') #4 /opt/wwwroot/phpMyAdmin/libraries/classes/Core.php(744): PhpMyAdmin\Url::getCommon(Array) #5 /opt/wwwroot/phpMyAdmin/libraries/classes/Core.php(329): PhpMyAdmin\Core::linkURL('https://secure....') #6 /opt/wwwroot/phpMyAdmin/libraries/classes/Core.php(352): PhpMyAdmin\Core::getPHPDocLink('book.json.php') #7 /opt/wwwroot/phpMyAdmin/libraries/classes/Core.php(982): PhpMyAdmin\Core::warnMissingExtension('json', true) #8 /opt/www in /opt/wwwroot/phpMyAdmin/vendor/symfony/polyfill-mbstring/Mbstring.php on line 490
这是nextcloud
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the webserver log.

**Comment by xzhih** [comment]
不错，很高兴有你这样的小伙伴，根据自己的环境来调整脚本，然后成功运行。被很多人问得多了，很烦，有些人是纯小白还不愿意学习，还有就是不会根据错误解决问题。

然后稍微说一下，`进程检测的判断条件` 你修改的这位置，不太准确，因为你在使用 `ps` 命令搭配 `grep`  命令的时候，`grep` 是一个独立的进程，那么总会有 `mysqld` 这个字符串存在，所以 `wc -l` 的返回值至少是 1 ，你这样改之后，永远都会显示启动成功。还有就是，路由器这种 `shell` 环境的 `ps` 命令支持的参数很少，比如 `-A` 和 `-ef` 至少在我使用的 padavan 和 LEDE 都不支持。

**Comment by lvxj11** [comment]
收到你的回复很开心。
我测试了小米系统的ps和lede系统的ps指令，lede的ps指令的确只有3条参数可选。而小米系统的ps指令选项和参数是这个样子的
`********* simple selection *********  ********* selection by list *********
-A all processes                      -C by command name
-N negate selection                   -G by real group ID (supports names)
-a all w/ tty except session leaders  -U by real user ID (supports names)
-d all except session leaders         -g by session OR by effective group name
-e all processes                      -p by process ID
T  all processes on this terminal     -s processes in the sessions given
a  all w/ tty, including other users  -t by tty
g  OBSOLETE -- DO NOT USE             -u by effective user ID (supports names)
r  only running processes             U  processes for specified users
x  processes w/o controlling ttys     t  by tty
*********** output format **********  *********** long options ***********
-o,o user-defined  -f full            --Group --User --pid --cols --ppid
-j,j job control   s  signal          --group --user --sid --rows --info
-O,O preloaded -o  v  virtual memory  --cumulative --format --deselect
-l,l long          u  user-oriented   --sort --tty --forest --version
-F   extra full    X  registers       --heading --no-heading --context
                    ********* misc options *********
-V,V  show version      L  list format codes  f  ASCII art forest
-m,m,-L,-T,H  threads   S  children in sum    -y change -l format
-M,Z  security data     c  true command name  -c scheduling class
-w,w  wide output       n  numeric WCHAN,UID  -H process hierarchy `
根据测试如果添加参数aux或-ef可以达到和你原来代码一样的效果，而如果添加-A参数由于列表不包含进程参数所以grep进程不会显示后面的参数， 所以`wc-l `就可能返回0。而如果保持无参数ps，只返回当前终端的进程所以nginx和php会返回0不等于1会显示成功，mysqld正好有一个进程会显示失败不能继续执行脚本。

**Comment by lvxj11** [comment]
这是运行onmp时的情况
`root@XiaoQiang:~# ps -A | grep mysqld
16658 pts/0    00:00:01 mysqld `
这是关闭onmp时的情况
`root@XiaoQiang:~# onmp stop
onmp正在停止
onmp已停止
root@XiaoQiang:~# ps -A | grep mysqld
root@XiaoQiang:~# `
这是ps不加参数运行情况
`root@XiaoQiang:~# ps
  PID TTY          TIME CMD
19983 pts/0    00:00:00 ash
23278 pts/0    00:00:00 ps
root@XiaoQiang:~# `
这是`ps -A`运行情况
`root@XiaoQiang:~# ps -A
  PID TTY          TIME CMD
    1 ?        00:00:02 init
    2 ?        00:00:00 kthreadd
    3 ?        00:00:01 ksoftirqd/0
    4 ?        00:00:01 kworker/0:0
    6 ?        00:00:00 migration/0
    7 ?        00:00:00 migration/1
    8 ?        00:00:01 kworker/1:0
    9 ?        00:00:00 ksoftirqd/1
   10 ?        00:00:00 cpuset
   11 ?        00:00:00 khelper
   12 ?        00:00:00 kdevtmpfs
  117 ?        00:00:00 irq/202-msmdata
  311 ?        00:00:00 sync_supers
  313 ?        00:00:00 bdi-default
  314 ?        00:00:00 kintegrityd
  315 ?        00:00:00 crypto 
………… `
这是关闭onmp后`ps aux`运行情况
root@XiaoQiang:~# ps aux | grep mysqld
root     26211  0.0  0.1   2328   632 pts/0    S+   18:07   0:00 grep mysqld
root@XiaoQiang:~#
这是开启onmp后运行情况
`root@XiaoQiang:~# ps aux | grep mysqld
root     26606  6.1 10.2 470424 49828 pts/0    Sl   18:08   0:00 /opt/bin/mysqld --pid-file=/opt/var/run/mysqld.pid
root     26799  0.0  0.1   2328   632 pts/0    S+   18:08   0:00 grep mysqld
root@XiaoQiang:~# `

**Comment by lvxj11** [comment]
编辑的时候没问题，怎么一提交换行就没了？

**Comment by xzhih** [comment]
哦？那应该是你这小米固件的管道命令可能和正常的有少许不同，我有空重写个进程判断好了

**Comment by lvxj11** [comment]
管道命令应该没问题，主要是ps命令参数定义不同，普通openwrt的`ps`等效于小米的`ps aux`。而如果在小米上直接执行无参数`ps`因为得到的列表过于简略所以后面的`grep`查询不到关键词所以会出错。
